
ga_code : "UA-11483598-1"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

# seo data
title : Josh Somma's awesome website
description : Personal website of Josh Somma, London UK
url : https://joshsomma.com
